baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'gatordynamics'

[[menus.main]]
name = 'About Me'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = '/Projects'
weight = 20

[[menus.main]]
name = 'Thoughts'
pageRef = '/posts'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
